# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='internal id')),
                ('label', models.CharField(max_length=128, verbose_name='human readable label')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
