# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provapp', '0002_auto_20160405_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='docuLink',
            field=models.CharField(max_length=512, null=True, verbose_name='documentation link'),
        ),
        migrations.AddField(
            model_name='activity',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 5, 6, 51, 17, 698807)),
        ),
        migrations.AddField(
            model_name='activity',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 5, 6, 51, 17, 698772)),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(max_length=128, null=True, verbose_name='type of this activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='label',
            field=models.CharField(max_length=128, null=True, verbose_name='human readable label'),
        ),
    ]
