# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provapp', '0003_auto_20160405_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128, null=True)),
                ('type', models.CharField(choices=[('voprov:Project', 'voprov:Project'), ('prov:Person', 'prov:Person')], max_length=128, null=True)),
                ('description', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128, null=True)),
                ('type', models.CharField(choices=[('prov:Collection', 'prov:Collection'), ('voprov:dataSet', 'voprov:dataSet')], max_length=128, null=True)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('status', models.CharField(max_length=128, null=True)),
                ('dataType', models.CharField(max_length=128, null=True)),
                ('storageLocation', models.CharField(max_length=1024, null=True, verbose_name='storage location')),
            ],
        ),
        migrations.CreateModel(
            name='Used',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='docuLink',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='documentation link'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='label',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('obs:Observation', 'obs:Observation'), ('obs:Reduction', 'obs:Reduction'), ('obs:Classification', 'obs:Classification'), ('obs:Crossmatch', 'obs:Crossmatch'), ('calc:ChemicalPipeline', 'calc:ChemicalPipeline'), ('calc:Distances', 'calc:Distances'), ('other', 'other')], max_length=128, null=True),
        ),
    ]
