# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provapp', '0004_auto_20160405_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='hadMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Entity')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='provapp.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='wasAssociatedWith',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Activity')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='wasAttributedTo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Agent')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='wasDerivedFrom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Entity')),
                ('entity2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity1', to='provapp.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='WasGeneratedBy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Activity')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Entity')),
            ],
        ),
        migrations.AddField(
            model_name='used',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Activity'),
        ),
        migrations.AddField(
            model_name='used',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Entity'),
        ),
        migrations.AlterField(
            model_name='used',
            name='role',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
