# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provapp', '0005_auto_20160405_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='dataType',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='storageLocation',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='storage location'),
        ),
    ]
