# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vosi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='enabled',
        ),
    ]
