# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vosi', '0003_auto_20170908_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityOption',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('available', models.BooleanField(help_text='True if the service is available, else false')),
                ('note', models.CharField(blank=True, help_text='A status message', max_length=256, null=True)),
            ],
        ),
    ]
