# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vosi', '0004_availabilityoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='enabled',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vosi.AvailabilityOption'),
            preserve_default=False,
        ),
    ]
